using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ScheduleApp.Data.Migrations
{
    /// <inheritdoc />
    /// <summary>
    /// Makes Employee.Pin required (it's assigned on the ZKTeco biometric device before an
    /// employee can be added to ScheduleApp at all -- see that property's own doc comment,
    /// and Employee.cs/ScheduleDbContext.cs for the corresponding model-level change this
    /// migration catches up the schema to) and restores a real FK from
    /// ScheduleEntries.EmployeeId to Employees.Pin, now that Pin can carry the full unique
    /// constraint an FK target requires -- see ScheduleDbContext's own remarks on
    /// ScheduleEntry for why RekeyScheduleEntriesToEmployeePin (the previous migration)
    /// couldn't do this and had to drop the FK/navigation entirely instead.
    ///
    /// Up() guards first, same shape RekeyScheduleEntriesToEmployeePin's own guard uses:
    /// refuses to touch anything until every existing employee has a Pin, since there's no
    /// safe value to invent for one that doesn't. The old filtered index has to be dropped
    /// BEFORE AlterColumn, not after -- SQL Server refuses to ALTER COLUMN on Pin while any
    /// index still references it, full stop, regardless of which direction the nullability
    /// change goes; the new plain unique index only goes back on once the column itself is
    /// already NOT NULL. Down() below mirrors this in reverse for the exact same reason.
    ///
    /// IMPORTANT -- hand-written, not generated by `dotnet ef migrations add`: this
    /// environment has no .NET SDK/EF tooling to produce or verify one. Written the same way
    /// RekeyScheduleEntriesToEmployeePin was -- closely following this project's own existing
    /// migrations' patterns and cross-checked by hand against ScheduleDbContextModelSnapshot.cs
    /// -- but treat this as a draft until it's been run (or at least `dotnet build`-verified)
    /// against a real EF Core toolchain, ideally regenerated for real via
    /// `dotnet ef migrations add` once that's available, rather than trusted as-is against
    /// production data.
    /// </summary>
    public partial class RequireEmployeePin : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Refuses to proceed while any employee has no Pin -- there's no safe value to
            // backfill one with (unlike, say, a boolean flag with an obvious default). Run
            // the SELECT in this message by hand first if this throws: assign each listed
            // employee an Employee ID (from the ZKTeco device they're enrolled on), then
            // re-run this migration.
            migrationBuilder.Sql(@"
                IF EXISTS (SELECT 1 FROM [Employees] WHERE [Pin] IS NULL)
                BEGIN
                    THROW 50002, 'Cannot make Employee.Pin required: one or more employees have no Employee ID set. Find them with: SELECT Id, LastName, FirstName FROM Employees WHERE Pin IS NULL -- assign each an Employee ID, then re-run this migration.', 1;
                END
            ");

            // The filtered index (see RenameEmployeeLegacyIdToPin, the migration that
            // originally created it) has to go before the column can be altered at all --
            // SQL Server refuses ALTER COLUMN on Pin while any index still references it.
            // It's also obsolete on its own terms once Pin can't be NULL: the whole reason
            // it was filtered (see that migration's own remarks) was to let multiple
            // employees share a NULL Pin, which is moot now.
            migrationBuilder.DropIndex(
                name: "IX_Employees_Pin",
                table: "Employees");

            migrationBuilder.AlterColumn<int>(
                name: "Pin",
                table: "Employees",
                type: "int",
                nullable: false,
                oldClrType: typeof(int?),
                oldType: "int",
                oldNullable: true);

            // Plain UNIQUE, not filtered -- this is also what ScheduleEntries.EmployeeId's
            // own FK below actually needs as a target (SQL Server requires a full PRIMARY
            // KEY or UNIQUE CONSTRAINT/INDEX, not a filtered one).
            migrationBuilder.CreateIndex(
                name: "IX_Employees_Pin",
                table: "Employees",
                column: "Pin",
                unique: true);

            // Restores the FK RekeyScheduleEntriesToEmployeePin dropped -- targeting
            // Employees.Pin as an alternate key this time (HasPrincipalKey on the C# side --
            // see ScheduleDbContext's own remarks on ScheduleEntry), not Employees.Id the way
            // the original FK (before either of these two migrations) did. Named the same as
            // that original FK -- EF's own naming convention keys off the dependent-side FK
            // property (EmployeeId), not which principal column it targets, so
            // FK_ScheduleEntries_Employees_EmployeeId is what `dotnet ef migrations add`
            // would generate here too.
            migrationBuilder.AddForeignKey(
                name: "FK_ScheduleEntries_Employees_EmployeeId",
                table: "ScheduleEntries",
                column: "EmployeeId",
                principalTable: "Employees",
                principalColumn: "Pin",
                onDelete: ReferentialAction.Cascade);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_ScheduleEntries_Employees_EmployeeId",
                table: "ScheduleEntries");

            // Same "no index can reference Pin while it's being altered" rule as Up() above
            // -- dropped here, before AlterColumn, and only recreated (filtered again) once
            // the column is nullable again.
            migrationBuilder.DropIndex(
                name: "IX_Employees_Pin",
                table: "Employees");

            migrationBuilder.AlterColumn<int?>(
                name: "Pin",
                table: "Employees",
                type: "int",
                nullable: true,
                oldClrType: typeof(int),
                oldType: "int");

            // Restores the filtered index RenameEmployeeLegacyIdToPin originally created --
            // see that migration's own remarks for why it's filtered rather than plain.
            migrationBuilder.CreateIndex(
                name: "IX_Employees_Pin",
                table: "Employees",
                column: "Pin",
                unique: true,
                filter: "[Pin] IS NOT NULL");
        }
    }
}
