using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ScheduleApp.Data.Migrations
{
    /// <inheritdoc />
    /// <summary>
    /// Re-keys ScheduleEntries.EmployeeId from Employee.Id (the ScheduleApp database key)
    /// to Employee.Pin (the punch clock's own employee code) -- see ScheduleEntry.EmployeeId's
    /// own doc comment for the full reasoning, and ScheduleDbContext's own remarks on
    /// ScheduleEntry for why the FK/navigation this drops can't be replaced with an
    /// equivalent one against Pin.
    ///
    /// Up() guards first: an employee with existing ScheduleEntries but no Pin has nothing
    /// to migrate those rows to (see the guard's own THROW message for how to find and fix
    /// them), so this refuses to touch anything -- schema or data -- until that's resolved,
    /// rather than silently leaving stale Employee.Id values sitting in a column now read as
    /// Pin (which could quietly collide with a *different* employee's real Pin). The actual
    /// re-key (UPDATE, joined through the still-live Employees.Id -> ScheduleEntries.EmployeeId
    /// relationship) has to run AFTER DropForeignKey, not before -- while
    /// FK_ScheduleEntries_Employees_EmployeeId is still in place, SQL Server would check every
    /// rewritten row's new (Pin-valued) EmployeeId against Employees.Id and reject the update
    /// for any row where those two numbering schemes don't happen to coincide, which is most
    /// or all of them.
    ///
    /// IMPORTANT -- hand-written, not generated by `dotnet ef migrations add`: this
    /// environment has no .NET SDK/EF tooling to produce or verify one. Written by closely
    /// following this project's own existing migrations (RenameEmployeeLegacyIdToPin for the
    /// index-drop/recreate shape, FixLegacyOtherChargeAdjustmentTypeData for the raw-SQL data
    /// fix shape) and cross-checked by hand against ScheduleDbContextModelSnapshot.cs, but
    /// treat this as a draft until it's been run (or at least `dotnet build`-verified) against
    /// a real EF Core toolchain -- ideally regenerated for real via `dotnet ef migrations add`
    /// once that's available, rather than trusted as-is against production data.
    /// </summary>
    public partial class RekeyScheduleEntriesToEmployeePin : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Refuses to proceed -- schema or data -- while any employee has existing
            // ScheduleEntries but no Pin. Run the SELECT in this message by hand first if
            // this throws: assign each listed employee an Employee ID (Pin), then re-run
            // this migration.
            migrationBuilder.Sql(@"
                IF EXISTS (
                    SELECT 1
                    FROM [ScheduleEntries] se
                    INNER JOIN [Employees] e ON e.[Id] = se.[EmployeeId]
                    WHERE e.[Pin] IS NULL
                )
                BEGIN
                    THROW 50001, 'Cannot re-key ScheduleEntries to Employee.Pin: one or more employees with existing schedule entries have no Employee ID (Pin) set. Find them with: SELECT DISTINCT e.Id, e.LastName, e.FirstName FROM Employees e INNER JOIN ScheduleEntries se ON se.EmployeeId = e.Id WHERE e.Pin IS NULL -- assign each an Employee ID, then re-run this migration.', 1;
                END
            ");

            // No real FK/navigation is possible between ScheduleEntries.EmployeeId and
            // Employees.Pin (see ScheduleDbContext's own remarks on ScheduleEntry) -- SQL
            // Server requires an FK's target column under a full PRIMARY KEY or UNIQUE
            // CONSTRAINT, and Employee.Pin's own uniqueness is deliberately just a filtered
            // UNIQUE INDEX so multiple employees can share a null Pin. Dropped BEFORE the data
            // rewrite below, not after -- see this migration's own class-level remarks for why
            // that order (not the reverse) is what keeps the UPDATE from tripping the
            // still-live constraint on its way from Id-space into Pin-space. Losing
            // OnDelete(DeleteBehavior.Cascade) along with it is fine -- ScheduleRepository.
            // DeleteEmployeeAsync now deletes an employee's ScheduleEntries explicitly instead.
            migrationBuilder.DropForeignKey(
                name: "FK_ScheduleEntries_Employees_EmployeeId",
                table: "ScheduleEntries");

            // The guard above already confirmed every one of these joins finds a non-null
            // Pin to rewrite to.
            migrationBuilder.Sql(@"
                UPDATE se
                SET se.[EmployeeId] = e.[Pin]
                FROM [ScheduleEntries] se
                INNER JOIN [Employees] e ON e.[Id] = se.[EmployeeId];
            ");

            // IX_ScheduleEntries_EmployeeId_Date itself is untouched -- still the same two
            // columns, still unique, just "one row per (Pin, Date)" instead of "one row per
            // (Employee.Id, Date)" now that EmployeeId's own meaning changed underneath it.
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Best-effort reversal: re-derive each row's Employee.Id from the Pin currently
            // sitting in EmployeeId. A row whose Pin no longer matches any current employee
            // (e.g. that employee's Pin was reassigned or cleared after Up ran) is left as-is
            // rather than guessed at -- same "don't silently invent data" principle Up's own
            // guard applies in the other direction. Runs BEFORE AddForeignKey below, for the
            // mirror-image reason Up drops its FK before updating -- adding the constraint
            // back first would reject this same rewrite the instant it tried to write an
            // Employee.Id-space value into a column FK-checked against Employees.Id while
            // still holding a mix of old (Pin-space) values for any row this UPDATE hasn't
            // reached yet.
            migrationBuilder.Sql(@"
                UPDATE se
                SET se.[EmployeeId] = e.[Id]
                FROM [ScheduleEntries] se
                INNER JOIN [Employees] e ON e.[Pin] = se.[EmployeeId];
            ");

            migrationBuilder.AddForeignKey(
                name: "FK_ScheduleEntries_Employees_EmployeeId",
                table: "ScheduleEntries",
                column: "EmployeeId",
                principalTable: "Employees",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }
    }
}
