using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ScheduleApp.Data.Migrations
{
    /// <inheritdoc />
    /// <summary>
    /// Adds the employee-level buffer-default columns (Employee.
    /// ClockInBufferBeforeHours/ClockInBufferAfterHours/ClockOutBufferBeforeHours/
    /// ClockOutBufferAfterHours) -- the middle tier of the three-tier day/employee/
    /// policy cascade NormalBufferResolver resolves (see that class, and
    /// ScheduleDbContext's own remarks on the Employee entity for the corresponding
    /// model-level change this migration catches up the schema to). Nullable
    /// float columns, no default value, same shape as ScheduleEntry's own
    /// ClockInBufferBeforeHours/etc. (see AddNormalScheduleBufferOverrides) -- null
    /// is itself the meaningful "no employee-level default, fall through to the
    /// policy default" value here too, not a placeholder waiting to be replaced,
    /// so (same as that migration) there's no HasDefaultValue to match.
    ///
    /// IMPORTANT -- hand-written, not generated by `dotnet ef migrations add`: this
    /// environment has no .NET SDK/EF tooling to produce or verify one. Written the
    /// same way RequireEmployeePin/RekeyScheduleEntriesToEmployeePin were -- closely
    /// following this project's own existing migrations' patterns (in particular
    /// AddNormalScheduleBufferOverrides, which added the exact same four columns,
    /// same types, to ScheduleEntries) and cross-checked by hand against
    /// ScheduleDbContextModelSnapshot.cs -- but treat this as a draft until it's
    /// been run (or at least `dotnet build`-verified) against a real EF Core
    /// toolchain, ideally regenerated for real via `dotnet ef migrations add` once
    /// that's available, rather than trusted as-is against production data.
    /// </summary>
    public partial class AddEmployeeBufferDefaults : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<double>(
                name: "ClockInBufferBeforeHours",
                table: "Employees",
                type: "float",
                nullable: true);

            migrationBuilder.AddColumn<double>(
                name: "ClockInBufferAfterHours",
                table: "Employees",
                type: "float",
                nullable: true);

            migrationBuilder.AddColumn<double>(
                name: "ClockOutBufferBeforeHours",
                table: "Employees",
                type: "float",
                nullable: true);

            migrationBuilder.AddColumn<double>(
                name: "ClockOutBufferAfterHours",
                table: "Employees",
                type: "float",
                nullable: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "ClockInBufferBeforeHours",
                table: "Employees");

            migrationBuilder.DropColumn(
                name: "ClockInBufferAfterHours",
                table: "Employees");

            migrationBuilder.DropColumn(
                name: "ClockOutBufferBeforeHours",
                table: "Employees");

            migrationBuilder.DropColumn(
                name: "ClockOutBufferAfterHours",
                table: "Employees");
        }
    }
}
