<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>ScheduleApp.Excel</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EPPlus" />
    <PackageReference Include="System.Security.Cryptography.Xml" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ScheduleApp.Core\ScheduleApp.Core.csproj" />
    <ProjectReference Include="..\ScheduleApp.Payroll\ScheduleApp.Payroll.csproj" />
  </ItemGroup>

</Project>
