using System.Collections;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Reflection;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Input;
using System.Windows.Media;

namespace ScheduleApp.Desktop.Controls.FlexGrid;

/// <summary>
/// Prototype custom control in the shape of MESCIUS FlexGrid: bound columns, click-to-sort
/// headers, drag-to-resize columns, row selection (single/extended, click/ctrl/shift, and
/// arrow-key navigation), and in-cell editing (double-click or F2, commit on Enter/Tab,
/// cancel on Escape) -- all over a row-virtualizing panel so a large ItemsSource doesn't
/// realize a visual per row. Not wired into any real view; see FlexGridPrototypeWindow for
/// a runnable demo.
///
/// Cell values are read/written by reflection off <see cref="FlexGridColumn.BindingPath"/>
/// (see FlexGridReflection) rather than through WPF's Binding engine -- there's no
/// per-item container for a Binding's DataContext to hang off, since rows are realized and
/// recycled as plain visuals by FlexGridRowsPanel, not generated by an ItemsControl. That
/// also means an external change to an item's property (nothing routed through this grid)
/// isn't picked up until that row is next realized -- acceptable for a prototype, not for
/// production use against externally-mutated data.
///
/// <para><b>Unbound mode</b> -- FlexGrid's own way of working without a DataSource at all,
/// for data that's naturally cell-based rather than a list of objects (a manually-built
/// summary grid, a small spreadsheet-like editor). Active whenever <see cref="ItemsSource"/>
/// is null: set <see cref="RowCount"/> (or call <see cref="AddRow"/>/<see cref="InsertRow"/>/
/// <see cref="RemoveRow"/>) and read/write cells directly through the <c>this[row, column]</c>
/// indexer -- <see cref="FlexGridColumn.BindingPath"/> isn't needed, and
/// <see cref="FlexGridColumn.DataType"/> takes its place for choosing an editor and parsing
/// typed input. The two modes are mutually exclusive: the unbound members throw
/// InvalidOperationException while ItemsSource is set, and setting ItemsSource clears
/// whatever unbound data was there.</para>
/// </summary>
public partial class FlexDataGrid : UserControl
{
    private readonly FlexGridColumnHeadersPresenter _headerPresenter;
    private readonly FlexGridRowsPanel _rowsPanel;
    private readonly List<object> _items = [];
    private readonly FlexGridUnboundStore _unboundStore = new();
    private readonly HashSet<int> _selectedIndices = [];

    private FlexGridColumn? _sortColumn;
    private ListSortDirection _sortDirection = ListSortDirection.Ascending;
    private int _currentRowIndex = -1;
    private int _currentColumnIndex = -1;

    public FlexDataGrid()
    {
        InitializeComponent();

        Columns = [];
        Columns.CollectionChanged += OnColumnsChanged;

        // Two brushes from one accent colour, and they have to differ: the selected row
        // fills with the translucent one (so the cell text underneath stays readable) and
        // the current cell outlines itself with the opaque one. Using a single brush for
        // both -- as this did originally -- draws the current-cell border in exactly the
        // colour of the row highlight it sits on, i.e. invisibly.
        var accent = (TryFindResource("SystemAccentColorPrimaryBrush") as SolidColorBrush)?.Color
                     ?? Color.FromRgb(0x3B, 0x82, 0xF6);

        SelectionBrush = Freeze(new SolidColorBrush(Color.FromArgb(0x38, accent.R, accent.G, accent.B)));
        CurrentCellBrush = Freeze(new SolidColorBrush(accent));

        _headerPresenter = new FlexGridColumnHeadersPresenter(this);
        HeaderHost.Child = _headerPresenter;

        _rowsPanel = new FlexGridRowsPanel(this);
        BodyScrollViewer.Content = _rowsPanel;

        PreviewKeyDown += OnPreviewKeyDown;
    }

    public ObservableCollection<FlexGridColumn> Columns { get; private set; }

    public static readonly DependencyProperty ItemsSourceProperty = DependencyProperty.Register(
        nameof(ItemsSource), typeof(IEnumerable), typeof(FlexDataGrid),
        new PropertyMetadata(null, OnItemsSourceChanged));

    public IEnumerable? ItemsSource
    {
        get => (IEnumerable?)GetValue(ItemsSourceProperty);
        set => SetValue(ItemsSourceProperty, value);
    }

    public static readonly DependencyProperty RowHeightProperty = DependencyProperty.Register(
        nameof(RowHeight), typeof(double), typeof(FlexDataGrid),
        new PropertyMetadata(32.0, OnLayoutAffectingPropertyChanged));

    public double RowHeight
    {
        get => (double)GetValue(RowHeightProperty);
        set => SetValue(RowHeightProperty, value);
    }

    public static readonly DependencyProperty HeaderHeightProperty = DependencyProperty.Register(
        nameof(HeaderHeight), typeof(double), typeof(FlexDataGrid),
        new PropertyMetadata(34.0, OnLayoutAffectingPropertyChanged));

    public double HeaderHeight
    {
        get => (double)GetValue(HeaderHeightProperty);
        set => SetValue(HeaderHeightProperty, value);
    }

    public static readonly DependencyProperty IsReadOnlyProperty = DependencyProperty.Register(
        nameof(IsReadOnly), typeof(bool), typeof(FlexDataGrid), new PropertyMetadata(false));

    public bool IsReadOnly
    {
        get => (bool)GetValue(IsReadOnlyProperty);
        set => SetValue(IsReadOnlyProperty, value);
    }

    public static readonly DependencyProperty SelectionModeProperty = DependencyProperty.Register(
        nameof(SelectionMode), typeof(SelectionMode), typeof(FlexDataGrid),
        new PropertyMetadata(SelectionMode.Extended));

    public SelectionMode SelectionMode
    {
        get => (SelectionMode)GetValue(SelectionModeProperty);
        set => SetValue(SelectionModeProperty, value);
    }

    public static readonly DependencyProperty AutoGenerateColumnsProperty = DependencyProperty.Register(
        nameof(AutoGenerateColumns), typeof(bool), typeof(FlexDataGrid), new PropertyMetadata(false));

    /// <summary>When true and <see cref="Columns"/> is still empty by the time
    /// <see cref="ItemsSource"/> is set, one column per public readable property of the
    /// item type is generated automatically (read-only for properties with no public
    /// setter) -- FlexGrid's own AutoGenerateColumns.</summary>
    public bool AutoGenerateColumns
    {
        get => (bool)GetValue(AutoGenerateColumnsProperty);
        set => SetValue(AutoGenerateColumnsProperty, value);
    }

    public static readonly DependencyProperty AlternatingRowsBackgroundProperty = DependencyProperty.Register(
        nameof(AlternatingRowsBackground), typeof(Brush), typeof(FlexDataGrid),
        new PropertyMetadata(null, OnAlternatingRowsBackgroundChanged));

    public Brush? AlternatingRowsBackground
    {
        get => (Brush?)GetValue(AlternatingRowsBackgroundProperty);
        set => SetValue(AlternatingRowsBackgroundProperty, value);
    }

    public static readonly DependencyProperty SelectedItemProperty = DependencyProperty.Register(
        nameof(SelectedItem), typeof(object), typeof(FlexDataGrid),
        new FrameworkPropertyMetadata(null, FrameworkPropertyMetadataOptions.BindsTwoWayByDefault));

    /// <summary>The selected row's bound item. Bound mode only -- always null in unbound
    /// mode, where <see cref="SelectedRowIndex"/> is the thing to read instead.</summary>
    public object? SelectedItem
    {
        get => GetValue(SelectedItemProperty);
        set => SetValue(SelectedItemProperty, value);
    }

    public static readonly DependencyProperty SelectedRowIndexProperty = DependencyProperty.Register(
        nameof(SelectedRowIndex), typeof(int), typeof(FlexDataGrid),
        new FrameworkPropertyMetadata(-1, FrameworkPropertyMetadataOptions.BindsTwoWayByDefault));

    /// <summary>Index of the most recently selected row, or -1 when nothing is selected.
    /// Works in both modes -- the one selection property that means something in unbound
    /// mode, where there's no item for <see cref="SelectedItem"/> to point at.</summary>
    public int SelectedRowIndex
    {
        get => (int)GetValue(SelectedRowIndexProperty);
        set => SetValue(SelectedRowIndexProperty, value);
    }

    /// <summary>Bound mode only -- see <see cref="SelectedRowIndices"/> for the mode-agnostic
    /// equivalent.</summary>
    public IReadOnlyList<object> SelectedItems => _selectedIndices
        .OrderBy(i => i)
        .Where(i => i < _items.Count)
        .Select(i => _items[i])
        .ToList();

    public IReadOnlyList<int> SelectedRowIndices => _selectedIndices.OrderBy(i => i).ToList();

    public event EventHandler? SelectionChanged;

    /// <summary>Raised after a cell edit (text or checkbox) is successfully written back --
    /// to the underlying item in bound mode, to the unbound store otherwise.</summary>
    public event EventHandler<FlexGridCellEventArgs>? CellEdited;

    /// <summary>Number of rows currently shown: <see cref="ItemsSource"/>'s item count in
    /// bound mode, the unbound store's row count otherwise. The setter is unbound-mode only
    /// (throws InvalidOperationException while ItemsSource is set) and grows or shrinks the
    /// store, filling new rows with null cells -- FlexGrid's own <c>Rows.Count = n</c>.</summary>
    public int RowCount
    {
        get => ItemsSource is not null ? _items.Count : _unboundStore.RowCount;
        set
        {
            EnsureUnbound(nameof(RowCount));
            _unboundStore.SetRowCount(value, Columns.Count);
            OnUnboundRowsChanged();
        }
    }

    /// <summary>Unbound-mode cell access by (row, column) -- FlexGrid's own indexer. The
    /// getter works in either mode (bound mode reads through
    /// <see cref="FlexGridColumn.BindingPath"/>, same as a displayed cell); the setter is
    /// unbound-mode only, since a bound cell's value belongs to the underlying item.</summary>
    public object? this[int rowIndex, int columnIndex]
    {
        get => GetCellValue(rowIndex, columnIndex);
        set
        {
            EnsureUnbound("this[,]");
            _unboundStore.SetValue(rowIndex, columnIndex, value);
            _rowsPanel.RefreshRow(rowIndex);
        }
    }

    /// <summary>Appends one empty row. Unbound mode only.</summary>
    public void AddRow() => InsertRow(RowCount);

    /// <summary>Inserts one empty row at <paramref name="index"/>, shifting selection and
    /// the current cell to keep pointing at the same logical rows. Unbound mode only.</summary>
    public void InsertRow(int index)
    {
        EnsureUnbound(nameof(InsertRow));
        index = Math.Clamp(index, 0, RowCount);
        _unboundStore.InsertRow(index, Columns.Count);

        ReindexSelection(i => i >= index ? i + 1 : i);
        if (_currentRowIndex >= index) _currentRowIndex++;

        OnUnboundRowsChanged();
    }

    /// <summary>Removes the row at <paramref name="index"/>, shifting selection and the
    /// current cell to keep pointing at the same logical rows. Unbound mode only.</summary>
    public void RemoveRow(int index)
    {
        EnsureUnbound(nameof(RemoveRow));
        _unboundStore.RemoveRow(index);

        ReindexSelection(i => i == index ? (int?)null : i > index ? i - 1 : i);
        if (_currentRowIndex == index) _currentRowIndex = -1;
        else if (_currentRowIndex > index) _currentRowIndex--;

        OnUnboundRowsChanged();
    }

    /// <summary>Removes every unbound row. Unbound mode only.</summary>
    public void ClearRows()
    {
        EnsureUnbound(nameof(ClearRows));
        _unboundStore.Clear();
        _selectedIndices.Clear();
        _currentRowIndex = -1;
        OnUnboundRowsChanged();
    }

    private void EnsureUnbound(string memberName)
    {
        if (ItemsSource is not null)
            throw new InvalidOperationException($"FlexDataGrid.{memberName} is only valid in unbound mode (ItemsSource must be null).");
    }

    /// <summary>Remaps every selected row index through <paramref name="reindex"/> (null
    /// drops it) -- how InsertRow/RemoveRow keep the highlighted rows pointing at the same
    /// logical rows after the ones around them shift.</summary>
    private void ReindexSelection(Func<int, int?> reindex)
    {
        var remapped = _selectedIndices.Select(reindex).Where(i => i is not null).Select(i => i!.Value).ToHashSet();
        _selectedIndices.Clear();
        foreach (var i in remapped) _selectedIndices.Add(i);
    }

    private void OnUnboundRowsChanged()
    {
        var count = RowCount;
        var selectionChanged = _selectedIndices.RemoveWhere(i => i >= count) > 0;

        if (_currentRowIndex >= count) _currentRowIndex = -1;
        if (_currentRowIndex < 0) _currentColumnIndex = -1;
        SetCurrentValue(SelectedRowIndexProperty, _currentRowIndex);

        RefreshRowAppearance();
        _rowsPanel.InvalidateMeasure();

        if (selectionChanged) SelectionChanged?.Invoke(this, EventArgs.Empty);
    }

    private static SolidColorBrush Freeze(SolidColorBrush brush)
    {
        brush.Freeze();
        return brush;
    }

    /// <summary>Translucent accent fill behind a selected row.</summary>
    internal Brush SelectionBrush { get; }

    /// <summary>Opaque accent used for the current cell's outline -- deliberately distinct
    /// from <see cref="SelectionBrush"/>, which it is drawn on top of.</summary>
    internal Brush CurrentCellBrush { get; }

    internal Brush? AlternatingRowsBrush => AlternatingRowsBackground;

    internal bool IsRowSelected(int rowIndex) => _selectedIndices.Contains(rowIndex);

    /// <summary>The cell's current value: reflected off the bound item in bound mode, read
    /// from the unbound store otherwise.</summary>
    internal object? GetCellValue(int rowIndex, int columnIndex)
    {
        if (rowIndex < 0 || rowIndex >= RowCount || columnIndex < 0 || columnIndex >= Columns.Count) return null;

        var column = Columns[columnIndex];
        if (ItemsSource is null) return _unboundStore.GetValue(rowIndex, columnIndex);

        return column.BindingPath is null ? null : FlexGridReflection.GetValue(_items[rowIndex], column.BindingPath);
    }

    /// <summary>Whether this cell should render/edit as a checkbox -- the bound item's own
    /// property type in bound mode, <see cref="FlexGridColumn.DataType"/> otherwise (there's
    /// no property to infer it from in unbound mode).</summary>
    internal bool IsBooleanColumn(int rowIndex, int columnIndex)
    {
        var column = Columns[columnIndex];
        if (ItemsSource is null) return column.DataType == typeof(bool);

        return rowIndex >= 0 && rowIndex < _items.Count && column.BindingPath is not null &&
               FlexGridReflection.GetPropertyType(_items[rowIndex], column.BindingPath) == typeof(bool);
    }

    /// <summary>Immediate checkbox-cell commit (no edit-mode round trip needed for a
    /// boolean). Writes through to the bound item or the unbound store depending on mode.</summary>
    internal void SetBooleanCell(int rowIndex, int columnIndex, bool value)
    {
        var column = Columns[columnIndex];
        if (ItemsSource is not null)
        {
            if (column.BindingPath is null) return;
            FlexGridReflection.SetValue(_items[rowIndex], column.BindingPath, value);
        }
        else
        {
            _unboundStore.SetValue(rowIndex, columnIndex, value);
        }

        NotifyCellEdited(rowIndex, columnIndex);
    }

    /// <summary>The row/column the keyboard acts on -- what F2 opens for editing, what
    /// Tab/arrow keys move, and what <see cref="FlexGridRow"/> draws its current-cell
    /// border around. -1 when nothing has been clicked yet.</summary>
    internal int CurrentRowIndex => _currentRowIndex;
    internal int CurrentColumnIndex => _currentColumnIndex;

    internal void SetCurrentCell(int rowIndex, int columnIndex)
    {
        _currentRowIndex = rowIndex;
        _currentColumnIndex = columnIndex;
        RefreshCurrentCellIndicator();
    }

    /// <summary>Re-evaluates the current-cell border on every realized row -- cheap
    /// (InvalidateArrange, not a rebuild) since only its Visibility/position depends on
    /// CurrentRowIndex/CurrentColumnIndex, not the cells themselves.</summary>
    private void RefreshCurrentCellIndicator()
    {
        foreach (var row in _rowsPanel.RealizedRows)
            row.InvalidateArrange();
    }

    /// <summary>Commits whatever cell is currently mid-edit, if any -- what Tab/Up/Down
    /// call before moving, so a key press during an edit doesn't leave that row's TextBox
    /// behind, still open, with the current-cell pointer already moved elsewhere. Returns
    /// false only when a commit was attempted and failed to parse, in which case the caller
    /// should leave the edit in place rather than moving on.</summary>
    private bool TryCommitActiveEdit()
    {
        var editingRow = _rowsPanel.RealizedRows.FirstOrDefault(r => r.IsEditing);
        return editingRow is null || editingRow.CommitEdit();
    }

    internal void MoveCurrentCell(int rowIndex, int columnIndex, bool wrap = false)
    {
        if (wrap)
        {
            if (columnIndex >= Columns.Count) { columnIndex = 0; rowIndex++; }
            else if (columnIndex < 0) { columnIndex = Columns.Count - 1; rowIndex--; }
        }

        if (rowIndex < 0 || rowIndex >= RowCount || columnIndex < 0 || columnIndex >= Columns.Count)
            return;

        SelectRow(rowIndex, null);
        SetCurrentCell(rowIndex, columnIndex);
        _rowsPanel.MakeRowVisible(rowIndex);
    }

    /// <summary>Row-level selection, following the same click/ctrl-click/shift-click rules
    /// as MonthCalendarControl. <paramref name="mouseEvent"/> is null for keyboard-driven
    /// moves, which always behave like a plain click (replace selection).</summary>
    internal void SelectRow(int rowIndex, MouseButtonEventArgs? mouseEvent)
    {
        if (rowIndex < 0 || rowIndex >= RowCount) return;

        var modifiers = mouseEvent is null ? ModifierKeys.None : Keyboard.Modifiers;

        if (SelectionMode == SelectionMode.Single || modifiers == ModifierKeys.None)
        {
            _selectedIndices.Clear();
            _selectedIndices.Add(rowIndex);
        }
        else if (modifiers.HasFlag(ModifierKeys.Control))
        {
            if (!_selectedIndices.Add(rowIndex))
                _selectedIndices.Remove(rowIndex);
        }
        else if (modifiers.HasFlag(ModifierKeys.Shift) && _currentRowIndex >= 0)
        {
            _selectedIndices.Clear();
            var lo = Math.Min(_currentRowIndex, rowIndex);
            var hi = Math.Max(_currentRowIndex, rowIndex);
            for (var i = lo; i <= hi; i++) _selectedIndices.Add(i);
        }

        _currentRowIndex = rowIndex;
        SetCurrentValue(SelectedRowIndexProperty, rowIndex);
        SetCurrentValue(SelectedItemProperty, ItemsSource is not null ? _items[rowIndex] : null);
        RefreshRowAppearance();
        SelectionChanged?.Invoke(this, EventArgs.Empty);
    }

    internal void NotifyCellEdited(int rowIndex, int columnIndex) =>
        CellEdited?.Invoke(this, new FlexGridCellEventArgs(
            ItemsSource is not null ? _items[rowIndex] : null, rowIndex, columnIndex));

    /// <summary>Writes an edited cell's text back -- to the bound item's property in bound
    /// mode, parsed via <see cref="FlexGridColumn.DataType"/> into the unbound store
    /// otherwise. Returns false when the text failed to parse, so the row keeps the cell in
    /// edit mode instead of silently discarding what was typed.</summary>
    internal bool TryCommitCell(int rowIndex, int columnIndex, string text)
    {
        if (rowIndex < 0 || rowIndex >= RowCount) return true;

        var column = Columns[columnIndex];

        try
        {
            if (ItemsSource is not null)
            {
                if (column.BindingPath is null) return true;
                FlexGridReflection.SetValue(_items[rowIndex], column.BindingPath, text);
            }
            else
            {
                _unboundStore.SetValue(rowIndex, columnIndex, FlexGridReflection.ParseText(text, column.DataType));
            }
        }
        catch (Exception ex) when (ex is FormatException or OverflowException or ArgumentException or InvalidCastException)
        {
            return false;
        }

        NotifyCellEdited(rowIndex, columnIndex);
        return true;
    }

    internal void SortByColumn(int columnIndex)
    {
        var column = Columns[columnIndex];
        if (!column.CanSort) return;

        if (_sortColumn == column)
        {
            _sortDirection = _sortDirection == ListSortDirection.Ascending
                ? ListSortDirection.Descending
                : ListSortDirection.Ascending;
        }
        else
        {
            if (_sortColumn is not null) _sortColumn.SortDirection = null;
            _sortColumn = column;
            _sortDirection = ListSortDirection.Ascending;
        }
        column.SortDirection = _sortDirection;

        SortItems();
        _selectedIndices.Clear();
        _headerPresenter.Rebuild();
        _rowsPanel.InvalidateMeasure();
    }

    private void SortItems()
    {
        if (_sortColumn is null) return;

        if (ItemsSource is null)
        {
            _unboundStore.Sort(Columns.IndexOf(_sortColumn), _sortDirection);
            return;
        }

        if (_sortColumn.BindingPath is not { } path) return;
        var direction = _sortDirection;

        _items.Sort((a, b) =>
        {
            var result = Comparer<object?>.Default.Compare(
                FlexGridReflection.GetValue(a, path),
                FlexGridReflection.GetValue(b, path));
            return direction == ListSortDirection.Ascending ? result : -result;
        });
    }

    private void RefreshRowAppearance()
    {
        foreach (var row in _rowsPanel.RealizedRows)
            row.UpdateAppearance();
    }

    private void OnColumnsChanged(object? sender, NotifyCollectionChangedEventArgs e)
    {
        if (e.OldItems is not null)
            foreach (FlexGridColumn column in e.OldItems)
                column.PropertyChanged -= OnColumnPropertyChanged;

        if (e.NewItems is not null)
            foreach (FlexGridColumn column in e.NewItems)
                column.PropertyChanged += OnColumnPropertyChanged;

        _unboundStore.EnsureColumnCount(Columns.Count);
        _headerPresenter?.Rebuild();
        _rowsPanel?.InvalidateMeasure();
    }

    private void OnColumnPropertyChanged(object? sender, PropertyChangedEventArgs e)
    {
        if (e.PropertyName == nameof(FlexGridColumn.Width))
        {
            _headerPresenter.InvalidateMeasure();
            _rowsPanel.InvalidateMeasure();
        }
        else
        {
            _headerPresenter.Rebuild();
        }
    }

    private static void OnLayoutAffectingPropertyChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
    {
        var grid = (FlexDataGrid)d;
        grid._headerPresenter?.InvalidateMeasure();
        grid._rowsPanel?.InvalidateMeasure();
    }

    private static void OnAlternatingRowsBackgroundChanged(DependencyObject d, DependencyPropertyChangedEventArgs e) =>
        ((FlexDataGrid)d).RefreshRowAppearance();

    private static void OnItemsSourceChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
    {
        var grid = (FlexDataGrid)d;

        if (e.OldValue is INotifyCollectionChanged oldNotify)
            oldNotify.CollectionChanged -= grid.OnSourceCollectionChanged;
        if (e.NewValue is INotifyCollectionChanged newNotify)
            newNotify.CollectionChanged += grid.OnSourceCollectionChanged;

        // Switching into bound mode: whatever was in the unbound store no longer applies
        // (RowCount/GetCellValue/etc. are about to start reading _items instead), so drop
        // it rather than leave it around as stale state a later ItemsSource=null would
        // otherwise resurrect.
        if (e.NewValue is not null)
            grid._unboundStore.Clear();

        if (grid.AutoGenerateColumns && grid.Columns.Count == 0)
            grid.GenerateColumns(e.NewValue as IEnumerable);

        grid.RefreshItemsSnapshot();
    }

    private void OnSourceCollectionChanged(object? sender, NotifyCollectionChangedEventArgs e) => RefreshItemsSnapshot();

    private void GenerateColumns(IEnumerable? source)
    {
        var itemType = source?.GetType().GetInterfaces()
            .Concat([source.GetType()])
            .Where(t => t.IsGenericType && t.GetGenericTypeDefinition() == typeof(IEnumerable<>))
            .Select(t => t.GetGenericArguments()[0])
            .FirstOrDefault();

        if (itemType is null)
            itemType = source?.Cast<object>().FirstOrDefault()?.GetType();

        if (itemType is null) return;

        foreach (var property in itemType.GetProperties(BindingFlags.Public | BindingFlags.Instance))
        {
            if (!property.CanRead || property.GetIndexParameters().Length > 0) continue;

            Columns.Add(new FlexGridColumn
            {
                Header = FlexGridReflection.Humanize(property.Name),
                BindingPath = property.Name,
                IsReadOnly = !property.CanWrite,
            });
        }
    }

    private void RefreshItemsSnapshot()
    {
        _items.Clear();
        if (ItemsSource is not null)
            foreach (var item in ItemsSource)
                _items.Add(item);

        SortItems();
        _selectedIndices.Clear();
        _currentRowIndex = -1;
        _currentColumnIndex = -1;

        _rowsPanel.InvalidateMeasure();
    }

    // Attached directly to this UserControl (see the constructor), so as a tunneling event
    // it fires before any handler further down the tree -- including an active edit
    // TextBox's own PreviewKeyDown -- gets a chance to run. That's deliberate: Tab/Up/Down
    // are handled once, here, for both "a cell is merely selected" and "a cell is being
    // edited" (committing first via TryCommitActiveEdit in the latter case) instead of
    // duplicating -- and potentially disagreeing with -- per-editor logic.
    private void OnPreviewKeyDown(object sender, KeyEventArgs e)
    {
        switch (e.Key)
        {
            case Key.F2 when _currentRowIndex >= 0 && _currentColumnIndex >= 0:
                _rowsPanel.RealizedRows.FirstOrDefault(r => r.RowIndex == _currentRowIndex)?.BeginEdit(_currentColumnIndex);
                e.Handled = true;
                break;

            case Key.Tab when _currentRowIndex >= 0:
                if (!TryCommitActiveEdit()) return;
                var forward = Keyboard.Modifiers != ModifierKeys.Shift;
                MoveCurrentCell(_currentRowIndex, Math.Max(0, _currentColumnIndex) + (forward ? 1 : -1), wrap: true);
                e.Handled = true;
                break;

            case Key.Down:
                if (!TryCommitActiveEdit()) return;
                MoveCurrentCell(_currentRowIndex + 1, Math.Max(0, _currentColumnIndex));
                e.Handled = true;
                break;

            case Key.Up:
                if (!TryCommitActiveEdit()) return;
                MoveCurrentCell(_currentRowIndex - 1, Math.Max(0, _currentColumnIndex));
                e.Handled = true;
                break;
        }
    }
}
